import Taro from '@tarojs/taro'
import {Button,Slider,Switch,Text,View} from '@tarojs/components'
import {useState} from 'react'
import {cloudClient} from '../../cloud/client'
import {errorMessage} from '../../platform/error'
import {defaultSettings,loadSettings,resetSettings,saveSettings,type AppSettings} from '../../settings'
import './index.scss'

export default function SettingsPage(){
  const[settings,setSettings]=useState(loadSettings);const[loggedIn,setLoggedIn]=useState(cloudClient.isLoggedIn());const[loggingIn,setLoggingIn]=useState(false);const[deletionStatus,setDeletionStatus]=useState('')
  const update=<K extends keyof AppSettings>(key:K,value:AppSettings[K])=>{const next={...settings,[key]:value};setSettings(next);saveSettings(next)}
  const login=async()=>{setLoggingIn(true);try{const consent=await Taro.showModal({title:'云存档隐私说明',content:'云端仅保存 ROM SHA-256、存档正文、版本、设备名称和同步审计；不会上传 ROM。',confirmText:'同意并登录'});if(!consent.confirm)return;const system=await Taro.getDeviceInfo();await cloudClient.login(`${system.brand||'WeChat'} ${system.model||'device'}`);setLoggedIn(true);setSettings(loadSettings());Taro.showToast({title:'云服务已连接',icon:'success'})}catch(error){showError(error)}finally{setLoggingIn(false)}}
  const logout=async()=>{const result=await Taro.showModal({title:'退出云服务',content:'本地 ROM、本地存档和该账号的本地偏好不会删除。'});if(result.confirm){await cloudClient.logout();setLoggedIn(false);setSettings(loadSettings())}}
  const deleteAccount=async()=>{const first=await Taro.showModal({title:'删除全部云端数据',content:'将撤销所有设备会话并删除云存档、历史版本和设备记录。本地 ROM 与本地存档不会删除。',confirmText:'继续',confirmColor:'#d43c62'});if(!first.confirm)return;const second=await Taro.showModal({title:'再次确认',content:'云端数据进入删除流程后不能恢复。',confirmText:'确认删除',confirmColor:'#d43c62'});if(!second.confirm)return;const result=await cloudClient.requestAccountDeletion();setLoggedIn(false);setSettings(loadSettings());setDeletionStatus(result.status)}
  const checkDeletion=async()=>{const result=await cloudClient.deletionStatus();setDeletionStatus(result?.status??'无进行中的请求')}
  const restoreDefaults=async()=>{const result=await Taro.showModal({title:'恢复默认设置',content:'只重置当前账号的显示、音频和控制偏好，不影响 ROM 或存档。',confirmText:'恢复'});if(result.confirm)setSettings(resetSettings())}
  return <View className='page-shell settings-page'><Text className='eyebrow'>SYSTEM</Text><View className='page-title'>设置</View><Text className='page-subtitle'>当前配置：{loggedIn?'微信账号':'匿名本机'}</Text>
    <SettingGroup title='显示'><SegmentedRow title='画面缩放' value={settings.videoScaling} options={[['sharp','锐利像素'],['smooth','平滑缩放']]} onChange={value=>update('videoScaling',value)}/><SettingSwitch title='自动帧跳过' detail='负载过高时减少呈现，不跳过模拟' value={settings.autoFrameSkip} onChange={value=>update('autoFrameSkip',value)}/><SettingSwitch title='显示帧率' detail='仅用于运行诊断' value={settings.showFps} onChange={value=>update('showFps',value)}/></SettingGroup>
    <SettingGroup title='音频'><SettingSwitch title='声音' detail='一键静音，不停止游戏运行' value={settings.sound} onChange={value=>update('sound',value)}/><SettingSlider title='音量' value={settings.volume} minimum={0} maximum={100} suffix='%' onChange={value=>update('volume',value)}/><SegmentedRow title='音频缓冲' value={settings.audioBufferMode} options={[['low_latency','低延迟'],['stable','稳定']]} onChange={value=>update('audioBufferMode',value)}/></SettingGroup>
    <SettingGroup title='播放'><SegmentedRow title='运行速度' value={String(settings.fastForward)} options={[['1','1x'],['2','2x'],['3','3x'],['4','4x']]} onChange={value=>update('fastForward',Number(value) as AppSettings['fastForward'])}/><Text className='group-note'>快进时自动静音；缓冲与速度在下次进入播放器时生效。</Text></SettingGroup>
    <SettingGroup title='控制'><SettingSwitch title='触控反馈' detail='不支持的设备会静默降级' value={settings.haptics} onChange={value=>update('haptics',value)}/><SegmentedRow title='布局预设' value={settings.controlPreset} options={[['right_handed','右手'],['left_handed','左手'],['landscape','横屏']]} onChange={value=>update('controlPreset',value)}/><SettingSlider title='按键大小' value={settings.controlScale} minimum={80} maximum={120} suffix='%' onChange={value=>update('controlScale',value)}/><SettingSlider title='按键间距' value={settings.controlSpacing} minimum={80} maximum={120} suffix='%' onChange={value=>update('controlSpacing',value)}/><SettingSlider title='按键透明度' value={settings.controlOpacity} minimum={40} maximum={100} suffix='%' onChange={value=>update('controlOpacity',value)}/><Button className='inline-command' onClick={()=>restoreDefaults().catch(showError)}>恢复默认布局与设置</Button></SettingGroup>
    <SettingGroup title='存档'><SettingSwitch title='自动恢复点' detail='每 60 秒及进入后台时创建' value={settings.autoState} onChange={value=>update('autoState',value)}/></SettingGroup>
    <SettingGroup title='云同步'><View className='account-line'><View><Text className='setting-title'>{loggedIn?'已连接':'未连接'}</Text><Text className='setting-detail'>{loggedIn?'微信身份会话有效':'仅使用本地存档'}</Text></View>{loggedIn?<Button className='account-button' onClick={()=>logout().catch(showError)}>退出</Button>:<Button className='account-button connect' loading={loggingIn} onClick={login}>微信登录</Button>}</View><SettingSwitch title='电池存档自动同步' detail='明确开启后自动上传，不上传 ROM' disabled={!loggedIn} value={settings.cloudSync&&loggedIn} onChange={value=>update('cloudSync',value)}/><SettingSwitch title='状态存档同步' detail='独立开关；可能占用更多云空间' disabled={!loggedIn||!settings.cloudSync} value={settings.cloudStateSync&&settings.cloudSync&&loggedIn} onChange={value=>update('cloudStateSync',value)}/></SettingGroup>
    <SettingGroup title='隐私与存储'><CommandRow title='存储管理' detail='分类查看占用并安全清理' command='打开' onClick={()=>Taro.navigateTo({url:'/pages/storage/index'})}/><CommandRow title='运行诊断' detail='查看性能并导出脱敏诊断包' command='打开' onClick={()=>Taro.navigateTo({url:'/pages/diagnostics/index'})}/>{loggedIn&&<CommandRow title='删除云端账号数据' detail='本地文件不受影响' command='删除' danger onClick={()=>deleteAccount().catch(showError)}/>}<CommandRow title='删除进度' detail={deletionStatus||'可查询最近请求'} command='查询' onClick={()=>checkDeletion().catch(showError)}/></SettingGroup>
    <SettingGroup title='关于'><View className='about-line'><Text>MiniGBA</Text><Text className='mono'>0.1.0</Text></View><View className='about-line'><Text>核心</Text><Text className='mono'>mGBA 0.10.5 · MPL-2.0</Text></View><CommandRow title='mGBA 对应源码' detail='固定版本 26b7884b；复制公开源码地址' command='复制' onClick={()=>Taro.setClipboardData({data:'https://github.com/mgba-emu/mgba/tree/26b7884bc25a5933960f3cdcd98bac1ae14d42e2'})}/><View className='about-line'><Text>默认音量</Text><Text className='mono'>{defaultSettings.volume}%</Text></View></SettingGroup>
  </View>
}

function SettingGroup({title,children}:{title:string;children:React.ReactNode}){return <View className='setting-group'><View className='section-title'>{title}</View><View className='setting-lines'>{children}</View></View>}
function SettingSwitch({title,detail,value,onChange,disabled=false}:{title:string;detail:string;value:boolean;onChange:(value:boolean)=>void;disabled?:boolean}){return <View className={`setting-line ${disabled?'disabled':''}`}><View><Text className='setting-title'>{title}</Text><Text className='setting-detail'>{detail}</Text></View><Switch color='#1bb4a5' checked={value} disabled={disabled} onChange={event=>onChange(event.detail.value)}/></View>}
function SettingSlider({title,value,minimum,maximum,suffix,onChange}:{title:string;value:number;minimum:number;maximum:number;suffix:string;onChange:(value:number)=>void}){return <View className='slider-line'><View className='slider-heading'><Text className='setting-title'>{title}</Text><Text className='mono'>{value}{suffix}</Text></View><Slider min={minimum} max={maximum} step={5} value={value} activeColor='#1bb4a5' backgroundColor='#36413f' blockColor='#edf3f0' blockSize={18} onChange={event=>onChange(event.detail.value)}/></View>}
function SegmentedRow<T extends string>({title,value,options,onChange}:{title:string;value:T;options:Array<[T,string]>;onChange:(value:T)=>void}){return <View className='segmented-line'><Text className='setting-title'>{title}</Text><View className='segments'>{options.map(([id,label])=><Button key={id} className={value===id?'selected':''} onClick={()=>onChange(id)}>{label}</Button>)}</View></View>}
function CommandRow({title,detail,command,onClick,danger=false}:{title:string;detail:string;command:string;onClick:()=>void;danger?:boolean}){return <View className='account-line'><View><Text className='setting-title'>{title}</Text><Text className='setting-detail'>{detail}</Text></View><Button className={`account-button ${danger?'danger':''}`} onClick={onClick}>{command}</Button></View>}
const showError=(error:unknown)=>Taro.showModal({title:'设置操作失败',content:errorMessage(error),showCancel:false})
