import Taro,{useDidShow} from '@tarojs/taro'
import {Button,Text,View} from '@tarojs/components'
import {useCallback,useState} from 'react'
import type {SaveManifest,SyncTask} from '../../domain/models'
import {cloudClient} from '../../cloud/client'
import {syncService} from '../../cloud/sync-service'
import {loadSettings} from '../../settings'
import {libraryRepository,saveRepository,syncQueue} from '../../services'
import {dataRoot,ensureDirectory,readBytes,writeBytesAtomic} from '../../platform/fs'
import './index.scss'

type SaveRow=SaveManifest&{gameTitle:string;cloudState:string;conflictTask?:SyncTask}
export default function SavesPage(){
  const[rows,setRows]=useState<SaveRow[]>([])
  const refresh=useCallback(async()=>{const[manifests,games,tasks]=await Promise.all([saveRepository.list(),libraryRepository.list(),syncQueue.list()]);const names=new Map(games.map(game=>[game.romId,game]));setRows(manifests.map(item=>({...item,gameTitle:names.get(item.romId)?.title??'未知游戏',cloudState:names.get(item.romId)?.cloudState??'disabled',conflictTask:tasks.find(task=>task.romId===item.romId&&task.kind===item.kind&&task.slot===item.slot&&task.conflict)})))},[])
  useDidShow(()=>{refresh().catch(showError)})
  const removeLocal=async(row:SaveRow)=>{const result=await Taro.showModal({title:'删除本地存档',content:`${row.gameTitle} · ${label(row.kind,row.slot)}\n云端副本不会删除。`,confirmText:'删除',confirmColor:'#d43c62'});if(!result.confirm)return;await saveRepository.remove(row.romId,row.kind,row.slot);await refresh()}
  const exportSave=async(row:SaveRow)=>{const stored=await saveRepository.load(row.romId,row.kind,row.slot);if(!stored)throw new Error('本地存档不存在');const extension=row.kind==='battery'?'sav':'state';const directory=`${dataRoot}/exports`;await ensureDirectory(directory);const filePath=`${directory}/${row.romId.slice(0,12)}-${row.kind}-${row.slot}.${extension}`;await writeBytesAtomic(filePath,stored.bytes);await Taro.shareFileMessage({filePath,fileName:`${safeName(row.gameTitle)}-${row.slot}.${extension}`})}
  const importBattery=async(row:SaveRow)=>{const selection=await Taro.chooseMessageFile({count:1,type:'file',extension:['sav']});const file=selection.tempFiles[0];if(!file)return;if(file.size>1024*1024)throw new Error('.sav 超过 1 MiB 限制');const bytes=await readBytes(file.path);if(!bytes.length)throw new Error('不能导入空存档');const confirm=await Taro.showModal({title:'导入电池存档',content:'当前正式存档会自动保留为上一成功版本。游戏运行中请先退出播放器。',confirmText:'导入'});if(!confirm.confirm)return;const manifest=await saveRepository.commit(row.romId,'battery','current',bytes,row.coreBuildId||'external-sav',row.cloudRevision);await libraryRepository.setSaveState(row.romId,true,loadSettings().cloudSync?'pending':'disabled');if(loadSettings().cloudSync){await syncService.enqueue(manifest);syncService.runDue().catch(()=>undefined)}await refresh();Taro.showToast({title:'已导入',icon:'success'})}
  const restoreCloud=async(row:SaveRow)=>{const confirm=await Taro.showModal({title:'恢复云端存档',content:'当前本地版本会作为 previous 备份保留。',confirmText:'恢复'});if(!confirm.confirm)return;await syncService.restoreCloudBattery(row.romId);await refresh();Taro.showToast({title:'已恢复',icon:'success'})}
  const removeCloud=async(row:SaveRow)=>{const confirm=await Taro.showModal({title:'删除云存档',content:'只删除此槽位的云端存档头；本地文件不受影响。',confirmText:'删除云端',confirmColor:'#d43c62'});if(!confirm.confirm)return;await cloudClient.deleteSave(row.romId,row.kind,row.slot);await libraryRepository.setSaveState(row.romId,true,'disabled');await refresh()}
  const restoreHistory=async(row:SaveRow)=>{const versions=(await cloudClient.versions(row.romId,row.kind,row.slot)).slice(0,6);if(!versions.length)throw new Error('没有云端历史版本');let selected;try{selected=await Taro.showActionSheet({itemList:versions.map(item=>`r${item.revision} · ${formatDate(item.createdAt)} · ${item.deviceName||'未知设备'}`)})}catch{return}const version=versions[selected.tapIndex];if(!version)return;const confirm=await Taro.showModal({title:`恢复云端 r${version.revision}`,content:`${formatBytes(version.sizeBytes)}\n${version.checksum.slice(0,16)}\n恢复会在云端创建一个新的 revision，并备份当前本地版本。`,confirmText:'恢复'});if(!confirm.confirm)return;await syncService.restoreCloudVersion(row.romId,row.kind,row.slot,version.revision);await refresh()}
  const resolveConflict=async(row:SaveRow)=>{const task=row.conflictTask,remote=task?.conflict;if(!task||!remote)throw new Error('冲突记录不存在');const details=await Taro.showModal({title:'比较冲突版本',content:`本地  r${row.localRevision} / cloud-base ${row.cloudRevision}\n${formatBytes(row.sizeBytes)} / ${row.checksum.slice(0,12)}\n\n云端  r${remote.currentRevision} / ${remote.deviceName||'未知设备'}\n${formatBytes(remote.sizeBytes)} / ${remote.checksum.slice(0,12)}\n${formatDate(remote.updatedAt)}`,confirmText:'选择处理'});if(!details.confirm)return;let choice;try{choice=await Taro.showActionSheet({itemList:['保留本地并上传','使用云端并备份本地','暂不处理']})}catch{return}if(choice.tapIndex===0)await syncService.resolveKeepLocal(task.id);if(choice.tapIndex===1)await syncService.resolveUseCloud(task.id);await refresh()}
  const actions=async(row:SaveRow)=>{const items:string[]=[];if(row.conflictTask)items.push('处理同步冲突');items.push('导出文件');if(row.kind==='battery')items.push('导入 .sav');if(cloudClient.isLoggedIn()){if(!row.conflictTask)items.push('从云端恢复');items.push('云端历史版本','删除云端')}items.push('删除本地');let result;try{result=await Taro.showActionSheet({itemList:items})}catch{return}const action=items[result.tapIndex];if(action==='处理同步冲突')await resolveConflict(row);if(action==='导出文件')await exportSave(row);if(action==='导入 .sav')await importBattery(row);if(action==='从云端恢复')await restoreCloud(row);if(action==='云端历史版本')await restoreHistory(row);if(action==='删除云端')await removeCloud(row);if(action==='删除本地')await removeLocal(row)}
  return <View className='page-shell saves-page'><Text className='eyebrow'>SAVE VAULT</Text><View className='page-title'>存档</View><Text className='page-subtitle'>本地版本与云端状态</Text>
    <View className='save-summary'><View><Text className='summary-number'>{rows.length}</Text><Text>本地存档</Text></View><View><Text className='summary-number'>{formatBytes(rows.reduce((sum,row)=>sum+row.sizeBytes,0))}</Text><Text>占用空间</Text></View></View>
    <View className='section-title'>全部存档</View>{!rows.length?<View className='empty-state'>尚无存档</View>:<View className='save-list'>{rows.map(row=><View className='save-row' key={`${row.romId}-${row.kind}-${row.slot}`}>
      <View className={`save-type ${row.conflictTask?'conflict':''}`}><Text>{row.kind==='battery'?'BAT':row.kind==='auto_state'?'AUTO':'STATE'}</Text></View><View className='save-copy'><Text className='save-game'>{row.gameTitle}</Text><Text className='save-meta'>{label(row.kind,row.slot)} · {formatDate(row.updatedAt)}{row.conflictTask?' · 待处理冲突':''}</Text><Text className='save-detail mono'>local {row.localRevision} · cloud {row.cloudRevision} · {formatBytes(row.sizeBytes)} · {row.checksum.slice(0,8)}</Text></View><Button className='save-action' onClick={()=>actions(row).catch(showError)}>•••</Button>
    </View>)}</View>}
  </View>
}
const label=(kind:SaveManifest['kind'],slot:string)=>kind==='battery'?'电池存档':kind==='auto_state'?'自动恢复点':`状态槽 ${Number(slot)+1}`
const formatBytes=(bytes:number)=>bytes>=1048576?`${(bytes/1048576).toFixed(1)} MiB`:`${Math.max(1,Math.ceil(bytes/1024))} KiB`
const formatDate=(value:string)=>{const date=new Date(value);return`${date.getMonth()+1}/${date.getDate()} ${String(date.getHours()).padStart(2,'0')}:${String(date.getMinutes()).padStart(2,'0')}`}
const safeName=(value:string)=>value.replace(/[\\/:*?"<>|]/g,'_').slice(0,40)||'minigba-save'
const showError=(error:unknown)=>Taro.showModal({title:'存档操作失败',content:error instanceof Error?error.message:String(error),showCancel:false})
